// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_aRqUcgbI0q_q3_rcZcwj_XwsaO97yPk',
    appId: '1:1038030620370:web:d5510d5da1b127475bcf0b',
    messagingSenderId: '1038030620370',
    projectId: 'bloc-f4498',
    authDomain: 'bloc-f4498.firebaseapp.com',
    storageBucket: 'bloc-f4498.appspot.com',
    measurementId: 'G-ZZZ2JN9C1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFgMJ7oJfJZ7QYUDzbkwT9MCGN-yzofXI',
    appId: '1:1038030620370:android:60ceb6ca95900d275bcf0b',
    messagingSenderId: '1038030620370',
    projectId: 'bloc-f4498',
    storageBucket: 'bloc-f4498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCraRGIyNdfIi_AWtAV5lFYF0Ibloq0tEs',
    appId: '1:1038030620370:ios:483b50442cb331d35bcf0b',
    messagingSenderId: '1038030620370',
    projectId: 'bloc-f4498',
    storageBucket: 'bloc-f4498.appspot.com',
    iosBundleId: 'com.example.bloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCraRGIyNdfIi_AWtAV5lFYF0Ibloq0tEs',
    appId: '1:1038030620370:ios:483b50442cb331d35bcf0b',
    messagingSenderId: '1038030620370',
    projectId: 'bloc-f4498',
    storageBucket: 'bloc-f4498.appspot.com',
    iosBundleId: 'com.example.bloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_aRqUcgbI0q_q3_rcZcwj_XwsaO97yPk',
    appId: '1:1038030620370:web:ded56e3d571620a35bcf0b',
    messagingSenderId: '1038030620370',
    projectId: 'bloc-f4498',
    authDomain: 'bloc-f4498.firebaseapp.com',
    storageBucket: 'bloc-f4498.appspot.com',
    measurementId: 'G-28K9K7Z872',
  );
}
