name: library_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.2.0
  icons_launcher: ^2.1.7
  image_picker: ^1.1.2
  firebase_storage: ^12.0.0
  firebase_app_check: ^0.3.0+4
  flutter_image_compress: ^2.3.0
  provider: ^6.1.2
  video_player: ^2.9.1
  chewie: ^1.8.3
  fl_chart: ^0.69.0
  awesome_snackbar_content: ^0.1.3
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^3.1.1
  cached_network_image: ^3.4.0

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    -  assets/
    -  assets/images/
  
